apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "frontend"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: "frontend"
    spec:
      containers:
        - name: app-nginx
          image: nginx 
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
           - containerPort: 80
